[workspace]
members = ["exercises/*/*", "helpers/common", "helpers/mdbook-exercise-linker", "helpers/ticket_fields"]

resolver = "2"


[profile.dev.package.copy]
overflow-checks = true

[profile.dev]
overflow-checks = false